# Generated by Django 4.2.3 on 2023-07-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('id_empleado', models.IntegerField(unique=True)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('horas_trabajadas', models.IntegerField()),
                ('otro_campo', models.CharField(max_length=255)),
            ],
        ),
    ]
