# Generated by Django 4.2.3 on 2023-07-06 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='otro_campo',
            new_name='puesto',
        ),
    ]
